### ISSUE TITLE
Further issues on loss of rabbit connection

### ISSUE THREAD

**Issue by fractalcat** [anchor/ceilometer-publisher-rabbitmq#8]
Looks potentially related to https://github.com/pika/pika/issues/518 and/or https://github.com/pika/pika/issues/490.

```
2015-01-07 04:48:47.107 32868 DEBUG ceilometer_publisher_rabbitmq.queue [-] Queue Publisher got sample publish_samples /usr/lib/python2.7/site-packages/ceilometer_publisher_rabbitmq/queue.py:87
2015-01-07 04:48:47.107 32868 DEBUG pika.callback [-] Incremented callback reference counter: {'callback': <bound method BlockingChannel._on_rpc_complete of <pika.adapters.blocking_connection.BlockingChannel object at 0x33c9590>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 25} add /usr/lib/python2.7/site-packages/pika/callback.py:152
2015-01-07 04:48:47.108 32868 DEBUG pika.callback [-] Incremented callback reference counter: {'callback': <bound method BlockingChannel._on_rpc_complete of <pika.adapters.blocking_connection.BlockingChannel object at 0x33c9590>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 97045} add /usr/lib/python2.7/site-packages/pika/callback.py:152
2015-01-07 04:48:47.226 32868 ERROR ceilometer.pipeline [-] Pipeline meter_sink: Continue after error from publisher <ceilometer_publisher_rabbitmq.queue.QueuePublisher object at 0x32062d0>
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline Traceback (most recent call last):
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/ceilometer/pipeline.py", line 304, in _publish_samples
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline     p.publish_samples(ctxt, transformed_samples)
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/ceilometer_publisher_rabbitmq/queue.py", line 89, in publish_samples
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline     while not self.publish_sample(message):
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/ceilometer_publisher_rabbitmq/queue.py", line 75, in publish_sample
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline     mandatory=True)
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 553, in basic_publish
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline     (properties, body))
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1141, in _rpc
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline     self._wait_on_response(method_frame))
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1159, in _send_method
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline     self.connection.send_method(self.channel_number, method_frame, content)
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 274, in send_method
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline     self._send_method(channel_number, method_frame, content)
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/pika/connection.py", line 1503, in _send_method
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline     self._send_frame(frame.Method(channel_number, method_frame))
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 417, in _send_frame
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline     super(BlockingConnection, self)._send_frame(frame_value)
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/pika/connection.py", line 1490, in _send_frame
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline     self._flush_outbound()
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 377, in _flush_outbound
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline     if self._handle_write():
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline   File "/usr/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 360, in _handle_write
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline     self.socket.sendall(frame)
2015-01-07 04:48:47.226 32868 TRACE ceilometer.pipeline AttributeError: 'NoneType' object has no attribute 'sendall'
```

**Comment by fractalcat** [comment]
Fixed in #9 and #15.
